name: Atualizar JSON

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Grant write permission to contents

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update JSON
      run: |
        # Update your JSON file here
        echo '{"key": "value"}' > dados.json

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add dados.json
        git commit -m 'Atualizando JSON automaticamente'
        git push
