name: Atualizar Dados do Campeonato

on:
  push:
    branches:
      - main # Aqui você pode mudar para outra branch, se necessário

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Criar arquivo JSON com dados
        run: echo '{"mensagem": "Olá, GitHub Actions!"}' > dados.json

      - name: Commit e Push das alterações
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dados.json
          git commit -m "Atualização automática dos dados" || echo "Nada para commit"
          git push
